trigger:
- main

pool:
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - visualstudio

variables:
  - group: build

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.301'
    performMultiLevelLookup: true

- task: NuGetCommand@2
  displayName: 'Install Yeetnite Launcher Dependencies'
  inputs:
    restoreSolution: '$(build.solution)'

- task: MSBuild@1
  inputs:
    solution: '$(build.solution)'
    msbuildVersion: '17.0'
    msbuildArchitecture: 'x64'
    configuration: '$(build.configuration)'
    platform: '$(build.platform)'
    clean: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.msbuildOutputDirectory)'
    includeRootFolder: false
    archiveType: '7z'
    sevenZipCompression: 'ultra'
    archiveFile: 'Yeetnite Launcher.7z'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Upload Release'
  inputs:
    PathtoPublish: 'Yeetnite Launcher.7z'
    ArtifactName: 'Yeetnite Launcher'
    publishLocation: 'Container'
