trigger:
- main

pool:
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - visualstudio

variables:
  solution: 'Yeetnite Launcher.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  stagingDirectory: 'packages'
  signingCertificate: 'yeetnite-team.pfx'
  msbuildOutputDirectory: 'x64\Release\YeetniteLauncher'
  packagesDirectory: 'packages'
  msixOutputPath: '$(packagesDirectory)\Yeetnite Launcher.msix'

steps:
- task: NuGetCommand@2
  displayName: 'Install Yeetnite Launcher Dependencies'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Compile Yeetnite Launcher'
  inputs:
    solution: '$(solution)'
    vsVersion: '17.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildArchitecture: 'x64'

- task: MsixPackaging@1
  displayName: 'Package Yeetnite Launcher'
  inputs:
    outputPath: '$(msixOutputPath)'
    buildSolution: false
    inputDirectory: '$(msbuildOutputDirectory)'
    generateBundle: false
    updateAppVersion: false

- task: MsixSigning@1
  displayName: 'Sign Installer Package'
  inputs:
    package: '$(msixOutputPath)'
    certificate: '$(signingCertificate)'
    passwordVariable: 'signingCertificatePassword'

- task: PublishBuildArtifacts@1
  displayName: 'Upload Release'
  inputs:
    PathtoPublish: '$(msixOutputPath)'
    ArtifactName: 'Yeetnite Launcher'
    publishLocation: 'Container'