trigger:
- main

pool:
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - visualstudio

variables:
  - group: build
  - group: git

resources:
  pipelines:
    - pipeline: updateMetadata
      source: 'Update Version Metadata'
      trigger:
       branches:
       - main
       - azure-devops

steps:
- task: NuGetCommand@2
  displayName: 'Install Yeetnite Launcher Dependencies'
  inputs:
    restoreSolution: '$(build.solution)'

- task: VSBuild@1
  displayName: 'Compile Yeetnite Launcher'
  inputs:
    solution: '$(build.solution)'
    vsVersion: '17.0'
    platform: '$(build.platform)'
    configuration: '$(build.configuration)'
    clean: true
    msbuildArchitecture: 'x64'

- task: MsixPackaging@1
  inputs:
    outputPath: '$(build.msixOutputPath)'
    buildSolution: false
    inputDirectory: '$(build.msbuildOutputDirectory)'
    generateBundle: false
    updateAppVersion: true
    manifestFile: '$(build.manifestLocation)'
    appVersion: '$(version)'

- task: MsixSigning@1
  displayName: 'Sign Installer Package'
  inputs:
    package: '$(build.msixOutputPath)'
    certificate: '$(build.signingCertificate)'
    passwordVariable: 'build.signingCertificatePassword'

- task: PublishBuildArtifacts@1
  displayName: 'Upload Release'
  inputs:
    PathtoPublish: '$(build.msixOutputPath)'
    ArtifactName: 'Yeetnite Launcher'
    publishLocation: 'Container'