trigger:
- main

pool:
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - visualstudio

variables:
  solution: 'Yeetnite Launcher.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  stagingDirectory: 'packages'
  signingCertificate: 'yeetnite-team.pfx'

steps:
- task: NuGetCommand@2
  displayName: 'Install Yeetnite Launcher Dependencies'
  inputs:
    restoreSolution: '$(solution)'

- task: MsixPackaging@1
  inputs:
    outputPath: '$(stagingDirectory)\Yeetnite Launcher.msix'
    solution: '$(solution)'
    clean: true
    generateBundle: true
    buildConfiguration: 'release'
    buildForX86: false
    updateAppVersion: false
    appPackageDistributionMode: 'SideloadOnly'
    msbuildLocationMethod: 'version'
    msbuildVersion: 'latest'
    msbuildArchitecture: 'x64'

- task: MsixSigning@1
  inputs:
    package: '$(stagingDirectory)\Yeetnite Launcher.msix'
    certificate: '$(signingCertificate)'
    passwordVariable: 'signingCertificatePassword'