trigger:
- main

pool:
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - visualstudio

variables:
  - group: build
  - group: git

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Install Azure CLI DevOps Extension
      az extension add --name azure-devops
      # Make sure we can get the PAT
      echo "personal access token is $(build.azurePAT)"
      # Login using Personal Access Token
      echo "$(build.azurePAT)" | az devops login --organization https://dev.azure.com/yeetnite/
      # Update Package Version
      az pipelines variable-group variable update --organization https://dev.azure.com/yeetnite/ --project "Yeetnite Launcher" --id 2 --name version --value $(git describe).substring(9)
      # Update Latest Tag Commit Hash
      az pipelines variable-group variable update --organization https://dev.azure.com/yeetnite/ --project "Yeetnite Launcher" --id 2 --name commitSHA --value $(git log $(git describe) -1 --pretty=%H)
    failOnStderr: true

- task: NuGetCommand@2
  displayName: 'Install Yeetnite Launcher Dependencies'
  inputs:
    restoreSolution: '$(build.solution)'

- task: VSBuild@1
  displayName: 'Compile Yeetnite Launcher'
  inputs:
    solution: '$(build.solution)'
    vsVersion: '17.0'
    platform: '$(build.platform)'
    configuration: '$(build.configuration)'
    clean: true
    msbuildArchitecture: 'x64'

- task: MsixPackaging@1
  inputs:
    outputPath: '$(build.msixOutputPath)'
    buildSolution: false
    inputDirectory: '$(build.msbuildOutputDirectory)'
    generateBundle: false
    updateAppVersion: true
    manifestFile: '$(build.manifestLocation)'
    appVersion: '$(version)'

- task: MsixSigning@1
  displayName: 'Sign Installer Package'
  inputs:
    package: '$(build.msixOutputPath)'
    certificate: '$(build.signingCertificate)'
    passwordVariable: 'build.signingCertificatePassword'

- task: PublishBuildArtifacts@1
  displayName: 'Upload Release'
  inputs:
    PathtoPublish: '$(build.msixOutputPath)'
    ArtifactName: 'Yeetnite Launcher'
    publishLocation: 'Container'